# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Adrien Bak
tagline:             Homepage
description:         'Where I put stuff I will later be ashamed of'
url:                 http://www.abak.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Adrien Bak
  url:               http://www.abak.io
  email:             adrien.bak@gmail.com

# Custom vars
version:             1.0.0

#analytics
ga:
  id:                UA-55822463-1
  domain:            abak.io

social:
  github:            https://github.com/abak
  email:             adrien.bak@gmail.com

pacbackup:
  url:               http://www.abak.io/pacbackup

gems:                [jekyll-paginate]

