# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Adrien Bak
tagline:             Homepage
description:         'A page about stuff'
url:                 http://www.abak.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Adrien Bak
  url:               http://www.abak.io
  email:             adrien.bak@gmail.com

# Custom vars
version:            1.0.0

#analytics
ga:
  id:                UA-55822463-1
  domain:            abak.io

social:
  github:         https://github.com/abak
  email:          adrien.bak@gmail.com